import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/Toast";
import MobileMenu from "@/components/MobileMenu";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
    >
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900 antialiased">
        <Providers>
          {children}
          <Toaster position="top-center" />
          <MobileMenu />
          {/* @ts-expect-error Server Component */}
          <Navbar />
        </Providers>
        <div className="h-40 md:hidden"></div>
      </body>
    </html>
  );
}
